### PR TITLE
Introduce plan_transform

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by dlfivefifty** [comment]
@jagot any thoughts? This is to clean up the notion of transform. That is, we factorization of a quasimatrix now reduces to `plan_transform`.

It should also support multi-dimensional transforms a la `plan_fft`.

**Comment by dlfivefifty** [comment]
@MikaelSlevinsky

**Comment by jagot** [comment]
Without understanding everything in detail, I think it looks fine. I don't really use the internals, and It seems the interface stays the same? With `expand` and `transform` as added convenience wrappers.

**Comment by dlfivefifty** [comment]
I decided to leave it `Derivative` for now (need to remove `Diff` from LazyArrays.jl first)

**Pull request merged**
