### PR TITLE
Support algebra operations on expansions

### PR DESCRIPTION
**Pull request by dlfivefifty**
@jagot FYI, this will be a big change so let me know your thoughts.

At the moment it's just a quick prototype: I want to make it trait based, so that, for example, `view(f, 0.5:0.5:1)` is also treated as an expansion. I think this is doable via a `BroadcastStyle`, instead of overloading `broadcasted` directly.

### CODE REVIEW

**Comment by jagot** [comment]
I think it looks a lot like the _ad hoc_ thing I have in Atoms.jl: https://github.com/JuliaAtoms/Atoms.jl/blob/compact-bases/src/radial_orbitals.jl#L2 (and also in CompactBases.jl: https://github.com/JuliaApproximation/CompactBases.jl/blob/master/src/types.jl), so I think it is a good idea to upstream the type definitions to ContinuumArrays.jl. Maybe also add the higher-order tensor case, i.e. `const Expansion{T,N,Space<:Basis,Coeffs<:AbstractArray{T,N}} = ApplyQuasiVector{T,typeof(*),<:Tuple{Space,Coeffs}}`? This would represent a 1-d curve in `N`-d space, if I'm thinking correctly.

The algebra is also very nice to have! Is `D^2` different from `D'D`? I would assume so, except for Dirichlet-0 boundary conditions.

Will the comparison of `Expansions` work with strict equality?

https://github.com/JuliaApproximation/ContinuumArrays.jl/blob/0c94353b79b6b5ee72f8834c503a03f5b77eba7f/src/bases/bases.jl#L192-L197

I.e. what type should `broadcastbasis` return?

And what is the difference between `+` and `-` in this case?:
https://github.com/JuliaApproximation/ContinuumArrays.jl/blob/0c94353b79b6b5ee72f8834c503a03f5b77eba7f/src/bases/bases.jl#L181

**Comment by dlfivefifty** [comment]
> The algebra is also very nice to have! Is D^2 different from D'D?

Yes. `D^2` doesn't really make sense for low order FEM bases: it's more appropriate for `Fourier` and `Chebyshev`. 

> Will the comparison of Expansions work with strict equality?

Yes: if `ST = T` then `ST \T` is `Eye(∞)`.

> And what is the difference between + and - in this case?

The idea was that one would only need to overload one of these.

**Comment by dlfivefifty** [comment]
> Maybe also add the higher-order tensor case

I don't follow: higher dimensions is a property of the axes. Unless you are proposing we support tensor algebra, that is, `QuasiArray{T,3}` can act on a `QuasiMatrix{T}`? That would require a lot of thought.

**Comment by jagot** [comment]
Yeah, I realized I was wrong; rather I meant supporting
```julia
const Expansion{T,N,Space<:Basis,Coeffs<:AbstractVecOrMat{T}} =
    ApplyQuasiVector{T,typeof(*),<:Tuple{Space,Coeffs}}
```
Then, if `Coeffs<:AbstractVector`, it would correspond to a single function expansion, whereas if `Coeffs<:AbstractMatrix`, each column of the matrix could be taken to be a separate function expansion (which is how I typically use it), or indeed a 1d curve in `N`-d space. Basically like the last figure here: https://juliaapproximation.github.io/CompactBases.jl/stable/bsplines/splines/

I think for functions in higher dimensions (this is really #15), i.e. beyond curves, you need to increase the number of quasi-axes as you increase the number of discrete axes (if that makes sense). I.e. a function mapping from 2d -> 1d would have 2 quasi-axes and 2 "basis function" axes (which we could denote e.g. `(2,2)->1`). These could either be constructed from tensor products of two `(1,1)->1` quasi-matrices, or a basis that is inherently `(2,2)->1`, such as RBFs.

Also mentioned in #15 is the case `(1,1)->2`, i.e a vector-valued function.

**Comment by dlfivefifty** [comment]
If the coefficients are a matrix, then the basis needs to be a 3-tensor, with 3-tensor times matrix multiplication defined. otherwise `*` doesn't make sense.

**Comment by jagot** [comment]
Well, then I would simply have `Expansions` as a convenience alias where the coefficients _are_ represented by a matrix, simply meaning a collection of function expansions.

**Comment by dlfivefifty** [comment]
Algebra has to make sense: if `A` is a `Basis <: QuasiMatrix` and `C` is a `Matrix`, then `A*C` is a `QuasiMatrix` with axes `axes(A*C) == (axes(A,1), axes(C,2))`. So yes it sounds fine, provided that each column is `A*C[:,j]`.

Where things are more complicated were if you wanted spherical harmonics with the coefficients represented as a matrix. This would _not_ makes sense as the basis is different for each column. So in that case it would be best to wrap the matrix as a block-vector and avoid the need to define tensors.

**Comment by jagot** [comment]
Fair enough. For spherical harmonics, the number of coefficients would be different though, for each irreducible representation? I.e. for `ell=0,1,2,...` the dimensions would be `1,3,5,...`. I guess in addition to storing the coefficients as a (column) block-vector, you would need to store the bases for each irrep in a (row) block-vector?

**Comment by dlfivefifty** [comment]
Just as a block-quasi-matrix, see https://github.com/JuliaApproximation/SphericalHarmonics.jl

**Pull request merged**
