### PR TITLE
Plotting for weighted bases

### PR DESCRIPTION
**Pull request by TSGut**
See https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/pull/73#issuecomment-846411390 and https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/pull/73#issuecomment-846556575

So I think this does actually just work as you said @dlfivefifty. At least testing it for weighted Zernike and weighted Jacobi gives the expected correct plots.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Can you add tests? See https://github.com/JuliaApproximation/ContinuumArrays.jl/blob/f3e0d96a4c890c7f541c3c9ce00a9f0f96bde4c0/test/runtests.jl#L600

We probably want to add tests to the quick-and-dirty weighted Chebyshev defined above

https://github.com/JuliaApproximation/ContinuumArrays.jl/blob/f3e0d96a4c890c7f541c3c9ce00a9f0f96bde4c0/test/runtests.jl#L515

**Comment by TSGut** [comment]
Yes, will do.

**Comment by TSGut** [comment]
This works for finite case and PaddedLayout infinite case. I'm not sure if there is an easy way to make this work for more generic infinite case of e.g. broadcast vectors as well but that doesn't seem supported for the unweighted bases either so that's probably fine for now.

**Comment by dlfivefifty** [comment]
Can you bump the patch version so I can merge and tag?

**Comment by TSGut** [comment]
I guess 0.7.5 is ok? done.

**Pull request merged**
